CREATE TABLE CMS_OFFLINE_STRUCTURE (
    STRUCTURE_ID VARCHAR(36) NOT NULL,
    RESOURCE_ID VARCHAR(36) NOT NULL,
    PARENT_ID VARCHAR(36) NOT NULL,
    RESOURCE_PATH VARCHAR(1024),
    STRUCTURE_STATE INT NOT NULL,
    DATE_RELEASED BIGINT NOT NULL,
    DATE_EXPIRED BIGINT NOT NULL,
    STRUCTURE_VERSION INT NOT NULL,
    CONSTRAINT PK_OFFLINE_STRUCTURE PRIMARY KEY (STRUCTURE_ID)
);

CREATE INDEX CMS_OFFLINE_STRUCTURE_01_IDX ON CMS_OFFLINE_STRUCTURE (RESOURCE_PATH);
CREATE INDEX CMS_OFFLINE_STRUCTURE_02_IDX ON CMS_OFFLINE_STRUCTURE (RESOURCE_ID);

CREATE TABLE CMS_ONLINE_STRUCTURE (
    STRUCTURE_ID VARCHAR(36) NOT NULL,
    RESOURCE_ID VARCHAR(36) NOT NULL,
    PARENT_ID VARCHAR(36) NOT NULL,
    RESOURCE_PATH VARCHAR(1024),
    STRUCTURE_STATE INT NOT NULL,
    DATE_RELEASED BIGINT NOT NULL,
    DATE_EXPIRED BIGINT NOT NULL,
    STRUCTURE_VERSION INT NOT NULL,
    CONSTRAINT PK_ONLINE_STRUCTURE PRIMARY KEY (STRUCTURE_ID)
);

CREATE INDEX CMS_ONLINE_STRUCTURE_01_IDX ON CMS_ONLINE_STRUCTURE (RESOURCE_PATH);

CREATE TABLE CMS_OFFLINE_RESOURCES (
    RESOURCE_ID VARCHAR(36) NOT NULL,
    RESOURCE_TYPE INT NOT NULL,
    RESOURCE_FLAGS INT NOT NULL,
    RESOURCE_STATE INT NOT NULL,
    RESOURCE_SIZE INT NOT NULL,
    DATE_CONTENT BIGINT NOT NULL,
    SIBLING_COUNT INT NOT NULL,
    DATE_CREATED BIGINT NOT NULL,
    DATE_LASTMODIFIED BIGINT NOT NULL,
    USER_CREATED VARCHAR(36) NOT NULL,
    USER_LASTMODIFIED VARCHAR(36) NOT NULL,
    PROJECT_LASTMODIFIED VARCHAR(36) NOT NULL,
    RESOURCE_VERSION INT NOT NULL,
    CONSTRAINT PK_OFFLINE_RESOURCES PRIMARY KEY(RESOURCE_ID)
);

CREATE TABLE CMS_ONLINE_RESOURCES (
    RESOURCE_ID VARCHAR(36) NOT NULL,
    RESOURCE_TYPE INT NOT NULL,
    RESOURCE_FLAGS INT NOT NULL,
    RESOURCE_STATE INT NOT NULL,
    RESOURCE_SIZE INT NOT NULL,
    DATE_CONTENT BIGINT NOT NULL,
    SIBLING_COUNT INT NOT NULL,
    DATE_CREATED BIGINT NOT NULL,
    DATE_LASTMODIFIED BIGINT NOT NULL,
    USER_CREATED VARCHAR(36) NOT NULL,
    USER_LASTMODIFIED VARCHAR(36) NOT NULL,
    PROJECT_LASTMODIFIED VARCHAR(36) NOT NULL,
    RESOURCE_VERSION INT NOT NULL,
    CONSTRAINT PK_ONLINE_RESOURCES PRIMARY KEY(RESOURCE_ID)
);

CREATE TABLE CMS_OFFLINE_CONTENTS (
    RESOURCE_ID VARCHAR(36) NOT NULL,
    FILE_CONTENT BLOB NOT NULL,
    CONSTRAINT PK_OFFLINE_CONTENTS PRIMARY KEY(RESOURCE_ID)
);

CREATE TABLE CMS_CONTENTS (
    RESOURCE_ID VARCHAR(36) NOT NULL,
    FILE_CONTENT BLOB NOT NULL,
    PUBLISH_TAG_FROM INT,
    PUBLISH_TAG_TO INT,
    ONLINE_FLAG INT,
    CONSTRAINT PK_CONTENTS PRIMARY KEY(RESOURCE_ID, PUBLISH_TAG_FROM)
);

CREATE TABLE CMS_RESOURCE_LOCKS (
    LOCK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RESOURCE_PATH VARCHAR(1024),
    USER_ID VARCHAR(36) NOT NULL,
    PROJECT_ID VARCHAR(36) NOT NULL,
    LOCK_TYPE INT NOT NULL
);

CREATE INDEX CMS_RESOURCE_LOCKS_01_IDX ON CMS_RESOURCE_LOCKS (RESOURCE_PATH);
